version: '2'

jobs: 
  build: 
    docker: 
      - image: circleci/python:3.7.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "requirements.txt" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
      - run:
          name: dependencies
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install --user -r requirements.txt
      - save_cache:
            paths:
              - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: 
            . venv/bin/activate
            docker-compose run app sh -c "python manage.py test"
      - store_artifacts:
          path: test-reports
          destination: test-reports